#!/bin/bash

# convert flac into mp3, or copy file in destination dir

file="$1" # source file
outputDir="$2" # output dir

if [ ${file: -5} = ".flac" ]
  then

    mkdir -p "$outputDir" # create outputDir if needed

    # get filename and replace file extension
    fileName=$(basename "$file")
    outputFile=${fileName%.flac}.mp3
    # echo "f: ${outputFile}"

    outputDir=$(echo "$outputDir" | sed 's:/*$::') # remove trailing slashs, to be consistent
    outputFile="${outputDir}/${outputFile}" # combine to obtain output filepath

    echo "outfile: ${outputFile}"


    # extract tags & image
    # use perl to remove lines that do not include an equal sign. That means multi-lines fields, e.g. lyrics.
    eval $(metaflac --export-tags-to - "$file" | perl -pe "s/^[^=]+$//g" | sed "s/=\(.*\)/=\"\1\"/")
    metaflac --export-picture-to "${outputFile%.mp3}.jpg" "$file"

    # flac: encode into mp3
    flac -cds "$file" | lame -S --noreplaygain -V 2 \
            --add-id3v2 --tt "$TITLE" --ta "$ARTIST" --tl "$ALBUM" \
            --ty "$DATE" --tn "$TRACKNUMBER/$TRACKTOTAL" --tg "$GENRE" \
            --tv "TPOS=$DISCNUMBER/$TOTALDISCS" \
            --ti "${outputFile%.mp3}.jpg" \
            - "$outputFile"

    rm "${outputFile%.mp3}.jpg" # delete cover image
  else # not flac: nothing
    echo "noflac: ${file}"
fi
