#!/bin/bash

# find in -type d -name "@eaDir" -print0 | xargs -0 rm -rf
# find $path -type f

path="$1"
outDir="$2"

find $path -type f -print0 | while read -d $'\0' file
do
  #  echo $file
  # replace input path with output path
  outfile=$(echo "$file" | sed "s:$path:$outDir:")
  # echo $outfile
  dir=$(dirname "$outfile")
  # echo $dir

  mkdir -p "$dir"

  if [ ${file: -5} == ".flac" ]
    then
      # replace file extension
      outfile=${outfile%.flac}.mp3
      echo $outfile
      eval $(metaflac --export-tags-to - "$file" | sed "s/=\(.*\)/='\1'/")
      metaflac --export-picture-to "${outfile%.mp3}.jpg" "$file"

      flac -cd "$file" | lame -S --noreplaygain -V 2 \
              --add-id3v2 --tt "$TITLE" --ta "$ARTIST" --tl "$ALBUM" \
              --ty "$DATE" --tn "$TRACKNUMBER" --tg "$GENRE" \
              --ti "${outfile%.mp3}.jpg" \
              - "$outfile"

      rm "${outfile%.mp3}.jpg"
    else
      cp "$file" "$outfile"
  fi
done
